application: www-eicg
module: default
version: 2014q2053-staging
runtime: python27
api_version: 1
threadsafe: true
instance_class: F1

automatic_scaling:
  max_idle_instances: 10
  min_pending_latency: 1s

default_expiration: "5d"

builtins:
- appstats: on
- admin_redirect: on
- remote_api: on

libraries:
- name: jinja2
  version: "latest"
- name: markupsafe
  version: "latest"
- name: lxml
  version: "latest"
- name: ssl
  version: "latest"

inbound_services:
- warmup

error_handlers:
  - file: inbox/templates/errors/default_error.html

  - error_code: over_quota
    file: inbox/templates/errors/over_quota.html

  - error_code: dos_api_denial
    file: inbox/templates/errors/dos.html

  - error_code: timeout
    file: inbox/templates/errors/timeout.html

handlers:
- url: /_ah/pipeline(/.*)?
  script: run.handlers._APP

- url: /favicon.ico
  static_files: inbox/static/img/favicon.ico
  upload: inbox/static/img/favicon.ico

- url: /robots.txt
  static_files: inbox/static/robots.txt
  upload: inbox/static/robots.txt

- url: /gae_mini_profiler/static
  static_dir: lib/gae_mini_profiler/static

- url: /gae_mini_profiler/.*
  script: lib.gae_mini_profiler.main.application

- url: /livecount/counter_admin
  script: run.livecount.counter_admin.application
  login: admin

- url: /livecount/.*
  script: run.livecount.counter.application
  login: admin

- url: /static
  static_dir: inbox/static
  http_headers:
    Access-Control-Allow-Origin: http://inboxcleaner.eforcers.com

#FIXME: This is processed by the backend, added here for dev app server testing
- url: /_ah/queue/deferred
  script: run.deferred_app
  login: admin

- url: /_ah/pipeline(/.*)?
  script: run.handlers._APP

#The landing is a static page
- url: /
  static_files: inbox/static/html/index.html
  upload: inbox/static/html/index.html

- url: .*
  script: run.inbox.app